### ISSUE TITLE
Problem installing, seemingly due to (missing?) folder "cooccurrence"

### ISSUE THREAD

**Issue by aan680** [williamleif/histwords#1]
bash-4.3$ pip install --user git+https://github.com/williamleif/histwords.git
You are using pip version 6.0.8, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/williamleif/histwords.git
  Cloning https://github.com/williamleif/histwords.git to /tmp/pip-GQOH9S-build
    Traceback (most recent call last):
      
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-GQOH9S-build/setup.py", line 7, in <module>
    
        ext_modules = cythonize(["googlengram/pullscripts/*.pyx", "cooccurrence/*.pyx"]),
    
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
    
        aliases=aliases)
    
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
    
        for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
    
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
    
        raise ValueError(error_msg)
    
    ValueError: 'cooccurrence/*.pyx' doesn't match any files
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-GQOH9S-build
bash-4.3$

**Comment by williamleif** [comment]
Sorry about that! The setup.py was outdated. Running setup.py will now work, but note that running setup.py will not actually "install" the histwords package (in the current setup); it will just install the necessary dependencies. You have to clone/download the code and use it locally. (The setup.py is currently just there to get the dependencies). 

In the future, I plan on a major refactor and releasing the code as a package that can be installed via pip.

Hope that makes sense!
