### ISSUE TITLE
code for visualizing results

### ISSUE THREAD

**Issue by okayzed** [williamleif/histwords#4]
very cool work!

1) I have been looking for the code that uses t-SNE to create the visualizations that are on the front page of the git repo, but can't find them. I've grepped for usage of sklearn (and for 'manifold' / 'tsne' key words) but only found sklearn's normalization in use - is the visualization code in the repo?

2) the visualization on the frontpage shows broadcast 1900s twice (in the middle panel) - is that intentional?

**Comment by williamleif** [comment]
Thanks @okayzed! 

1. The t-SNE code is unfortunately not in the repo. It was using sklearn's t-SNE but involved some messy hacks of the sklearn source code (to allow for the optimization to be initialized from a specified set of points and to fix certain points in the optimization), so it wasn't something that was easily shareable. I hope to release code for this at some point, but it is a bit far down my priority list unfortunately. 

2. Thanks for catching this. That was a typo in an older version of that figure.

**Comment by okayzed** [comment]
1. thanks - that's understandable. i put together a visualization with tsne in my fork:  https://github.com/okayzed/histwords/tree/tsne_viz/viz
(examples: http://imgur.com/a/DrGkd)

 a neighboring word's age is indicated via fading (the older the word, the lighter it is), while the similarity to the query word is indicated via fontsize. 

i'd like to create an interactive tool to explore relationships, but not sure what i will do just yet (or if)

**Comment by williamleif** [comment]
Awesome! If you feel motivated to make a pull request for this I would happily review the code in detail, but I understand if you want to push for something a bit bigger (e.g., an interactive tool).
