### ISSUE TITLE
how to load the pre-trained word vectors of histwords using gensim?

### ISSUE THREAD

**Issue by chengjun** [williamleif/histwords#8]
Thank you for your great work. I am wondering can I load the pre-trained word vectors of histwords using gensim?

**Comment by williamleif** [comment]
Hmm, do you mean to load the pre-trained vectors into Gensim to do more training? Or just to use the gensim API for KeyedVectors (https://radimrehurek.com/gensim/models/keyedvectors.html)?

If you just want to load them into a KeyedVectors vector you need to convert them to a format GenSim understands. For example, after loading in an Embedding object in HistWords you could run something like

```
with open("gensim_compat_file.txt", "w") as fp:
    for word in embeddings.iw:
        fp.write(word + " ".join(list(embeddings[word])) + "\n")
```

That should output the embeddings in "C text" format, which gensim can read.

**Comment by chengjun** [comment]
Thank you very much. This solution works perfectly. 

```python
from representations.embedding import Embedding

embeddings = Embedding.load("../data/english_all_sgns/1900")
vocab_size = len(embeddings.iw)
vector_size = len(embeddings[embeddings.iw[0]])

with open("../data/english_all_sgns_gensim_1900.txt", "w") as fp:
    fp.write(str(vocab_size) + " " + str(vector_size) + "\n")
    for word in embeddings.iw:
        fp.write(word + " " + " ".join(map(str, (embeddings[word]))) + "\n")
```
